name: build
on:
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    permissions: 
      checks: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: oracle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
      - name: Allow execution of gradle
        run: chmod +x ./gradlew
      - name: Build all classes
        run: ./gradlew build compileDebugUnitTestSources compileReleaseUnitTestSources -x test

  test:
    name: Run Unit Tests
    needs: build
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v3.13.0
        with:
          distribution: oracle
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
      - name: Allow execution of gradle
        run: chmod +x ./gradlew
      - name: Run Unit Tests
        run: ./gradlew test --continue
      - name: Build Report Debug Tests
        if: success() || failure()
        uses: scacap/action-surefire-report@v1.7.2
        with: 
          report_paths: '**/build/test-results/testDebugUnitTest/TEST-*.xml'
      - name: Build Report Release Tests
        if: success() || failure()
        uses: scacap/action-surefire-report@v1.7.2
        with: 
          report_paths: '**/build/test-results/testReleaseUnitTest/TEST-*.xml'
